#!/bin/bash

# Установка обновлений
echo "Установка обновлений"
apt-get update && sudo apt-get upgrade -y

# Настройка поддержки языка UTF-8
export LC_CTYPE=ru_RU.UTF-8
export LC_ALL=ru_RU.UTF-8

# Установка необходимых утилит
sudo apt-get install -y dialog wget curl nano sudo unzip
chmod +x ./lab/*
(
c=20
while [ $c -ne 120 ]
    do
        echo $c
        echo "###"
        echo "$c %"
        echo "###"
        ((c+=20))
        sleep 1
done
) |
dialog --title "Начало установки" --gauge "Пожалуйста подождите ...." 10 60 0


if [[ $EUID -ne 0 ]]; then
 echo "Этот скрипт должен быть запущен с правами root" 
 exit 1
else
 cmd=(dialog --separate-output --checklist "Пожалуйста выберите версию для установки:" 22 76 16)
 options=(1 "Установка Ministra Portal для Ubuntu 14.04 LTS" off # any option can be set to default to "on"
 2 "Установка Ministra Portal для Ubuntu 16.04 LTS" off
 3 "Exit" off)
 choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
 clear
 for choice in $choices
 do
 case $choice in
 1)
# Установка Ministra Portal для Ubuntu 14.04 LTS
 echo "Установка Ministra Portal для Ubuntu 14.04 LTS"
 ./lab/ministra14
;;

2)
# Установка Ministra Portal для Ubuntu 16.04 LTS
 echo "Установка Ministra Portal для Ubuntu 16.04 LTS"
./lab/ministra16
 ;;

# Выход
3)
exit
 ;;

 esac
 done
fi
