#!/bin/bash

# Color schema
red='\033[01;31m'
blue='\033[01;34m'
green='\033[01;32m'
norm='\033[00m'

# Temporary colors
RED="$(tput setaf 1)"
YELLOW="$(tput setaf 3)"
CYAN="$(tput setaf 6)"
NORMAL="$(tput sgr0)"

# smallLoader colors
CSI="\033["
CEND="${CSI}0m"
CRED="${CSI}1;31m"
CGREEN="${CSI}1;32m"
CYELLOW="${CSI}1;33m"
CPURPLE="${CSI}1;35m"
CCYAN="${CSI}1;36m"
CBROWN="${CSI}0;33m"

# smallLoader
smallLoader() {
    echo ""
    echo ""
    echo -ne '[ + + +             ] 3c \r'
    sleep 1
    echo -ne '[ + + + + + +       ] 2c \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] 1c \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] Нажмите [Enter] для продолжения... \r'
    echo -ne '\n'

    read -r
}



VER="5.4.1"
PRODUCT="Ministra Portal"
WEB="http://`ip route get 8.8.8.8 | awk '{print $NF; exit}'`/stalker_portal"
WAN="`wget -q -O - http://icanhazip.com/ | tail`"
LOCAL="`ip route get 8.8.8.8 | awk '{print $NF; exit}'`"

supported="    Debian 7, 8 on i386 and amd64
    Ubuntu 14.04 LTS "

skipyesno=0

# Ask a yes or no question
# if $skipyesno is 1, always Y
# if NONINTERACTIVE environment variable is 1, always Y
yesno () {
  # XXX skipyesno is a global set in the calling script
  # shellcheck disable=SC2154
  if [ "$skipyesno" = "1" ]; then
    return 0
  fi
  if [ "$NONINTERACTIVE" = "1" ]; then
    return 0
  fi
  while read -r line; do
    case $line in
      y|Y|Yes|YES|yes|yES|yEs|YeS|yeS) return 0
      ;;
      n|N|No|NO|no|nO) return 1
      ;;
      *)
      printf "\n${YELLOW}Пожалуйста нажмите ${CYAN}[y]${YELLOW} or ${CYAN}[n]${YELLOW}:${NORMAL} "
      ;;
    esac
  done
}

install_msg() {
cat <<EOF
  Welcome to the ${RED}$PRODUCT${NORMAL} installer, version ${RED}$VER${NORMAL}
  This script must be run on a freshly installed supported OS. It does not
  perform updates or upgrades (use your system package manager).
  The systems currently supported by install.sh are:
EOF
echo "${CYAN}$supported${NORMAL}"
cat <<EOF
  Ваша версия ОС не поддерживается, установка ${RED}НЕВОЗМОЖНА!${NORMAL}. Посмотреть более подробную информацию можете сдесь:
    ${UNDERLINE}${CYAN}https://github.com/betamaster2/ministra/docs/os-suport${NORMAL}
EOF

  printf " Продолжить? (y/n) "
  if ! yesno; then
    exit
  fi
}

if [ "$skipyesno" -ne 1 ] && [ -z "$setup_only" ]; then
  install_msg
fi


#
pass="12345"
source="http://linuxhelps.net/configs"

# Установка необходимых сервисов и пакетов
sudo apt-get install -y -u apache2 nginx wget nano curl nginx-extras unzip memcached php5 php5-mysql php-pear nodejs upstart && sudo pear channel-discover pear.phing.info && sudo pear install -Z phing/phing 
sleep 1

# Установка Pear
pear channel-discover pear.phing.info
pear install -Z phing/phing
sleep 1

# Установка NPM версии 2.5.11
sudo apt-get -y -u install npm
sudo npm install -g npm@2.15.11
sudo ln -s /usr/bin/nodejs /usr/bin/node


# Установка часовой зоны сервера
echo "Europe/Kiev" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

# Установка MySQL Server в неинтерактивном режиме. Пароль по-умолчанию для root пользователя "12345"
echo "mysql-server mysql-server/root_password password $pass" | sudo debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $pass" | sudo debconf-set-selections

apt-get install -y mysql-server > /dev/null

sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' /etc/mysql/my.cnf
mysql -uroot -p$pass -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'

service mysql restart

# Скачивание Ministra Portal
cd /var/www/html/
wget http://lab.itbox.bg/software/tv/ministra-5.4.1.zip
unzip ministra-5.4.1.zip
rm -rf *.zip

# Создание Базы данных MySql
mysql -uroot -p$pass -e "create database stalker_db"
mysql -uroot -p$pass -e "GRANT ALL PRIVILEGES ON stalker_db.* TO stalker@localhost IDENTIFIED BY '1' WITH GRANT OPTION;"

# Настройка MySQL
echo "max_allowed_packet = 32M" >> /etc/mysql/my.cnf

# Настройка PHP
echo "short_open_tag = On" >> /etc/php5/apache2/php.ini
a2enmod rewrite
apt-get purge libapache2-mod-php5filter > /dev/null

cd /etc/apache2/sites-enabled/
rm -rf *
wget $source/000-default.conf
cd /etc/apache2/
rm -rf ports.conf
wget $source/ports.conf
cd /etc/nginx/sites-available/
rm -rf default
wget $source/default
/etc/init.d/apache2 restart
/etc/init.d/nginx restart
/etc/init.d/apache2 restart
/etc/init.d/nginx restart


sleep 1
rm -rf /var/www/html/stalker_portal/admin/vendor
cd /var/www/html/stalker_portal/admin
wget http://lab.itbox.bg/software/tv/vendor.tar
tar -xvf vendor.tar
sleep 1

# Установка языка по-умолчанию
locale-gen ru_RU.utf8
service apache2 restart

# Установка Phing
cd /var/www/html/stalker_portal/deploy
sudo phing

sleep 1
smallLoader

echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""
echo -e "${CCYAN}[ Поздравляем! Установка завершена. Имя пользователя для входа в панель администратора: ${CRED}admin${CEND} ${CCYAN}Пароль: ${CRED}1${CEND} ${CCYAN}: ]${CEND}"
echo ""
echo -e "Внешний IP    : ${CGREEN}${WAN}${CEND}"
echo -e "Локальный IP  : ${CGREEN}${LOCAL}${CEND}"
echo -e "Пароль MySQL  : ${CGREEN}${pass}${CEND}"
echo -e "Портал        : ${CGREEN}${WEB}${CEND}"
echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""
